enum AppLanguage {
  bm,
  en,
}

extension AppLanguageCode on AppLanguage {
  String get code {
    switch (this) {
      case AppLanguage.bm:
        return 'BM';
      case AppLanguage.en:
        return 'EN';
    }
  }

  String get displayName {
    switch (this) {
      case AppLanguage.bm:
        return 'Bahasa Melayu';
      case AppLanguage.en:
        return 'English';
    }
  }
}

const _localizedText = <AppLanguage, Map<String, String>>{
  AppLanguage.en: <String, String>{
    'appName': 'TRACK',
    'appSubName': 'Malaysian Vehicle Plate Detection & Matching System',
    'navDashboard': 'Dashboard',
    'navScanner': 'Live Scanner',
    'navSearch': 'Manual Search',
    'navVehicles': 'Vehicles',
    'navUsers': 'Users',
    'navHistory': 'Audit History',
    'navSettings': 'Settings',
    'navProfile': 'Profile',
    'navLogout': 'Logout',
    'moreMenu': 'More',
    'demoRole': 'Demo Role',
    'roleUser': 'User',
    'roleAdmin': 'Admin',
    'roleSuperAdmin': 'Super Admin',
    'readOnlyBadge': 'Read-Only Mode',
    'loginTitle': 'Login to Track',
    'loginSubtitle': 'Select a role to launch demo session',
    'loginButton': 'Sign In Now',
    'totalVehicles': 'Total Vehicles',
    'activeCases': 'Active Cases',
    'todayScans': "Today's Scans",
    'manualSearches': 'Manual Searches',
    'quickNav': 'Quick Navigation',
    'openScannerBtn': 'Open Scanner',
    'searchPlateBtn': 'Search Plate',
    'vehiclesRepoBtn': 'Vehicles Repository',
    'auditHistoryBtn': 'Audit History',
    'recentMatchesTitle': 'Recent Case Matches & Audit Stream',
    'searchTitle': 'Plate Number Search',
    'searchPlaceholder': 'Example: ANN 7569 or W 8821 X',
    'searchBtn': 'Search Now',
    'matchFound': 'CASE MATCH FOUND',
    'possibleMatchFound': 'POSSIBLE MATCH FOUND',
    'noMatchTitle': 'NO MATCH FOUND',
    'noMatchDesc':
        'This plate number is not in the active repossession repository.',
    'plateNumber': 'Plate Number',
    'customerName': 'Customer Name',
    'vehicleDetails': 'Vehicle',
    'financeCompany': 'Finance Company',
    'caseReference': 'Case Reference',
    'priority': 'Priority',
    'liveScannerTitle': 'Live Malaysian ANPR Scanner',
    'cameraPreview': 'Live Camera Preview',
    'recentDetectionList': 'Recent Detections',
    'cameraFps': 'Camera FPS',
    'detectionFps': 'Detection FPS',
    'confidence': 'AI Confidence',
    'manageVehiclesTitle': 'Vehicle Repository Management',
    'manageVehiclesSub': 'Add, edit, import, or manage target vehicle cases.',
    'addVehicle': 'Add Vehicle',
    'importCsv': 'Import CSV',
    'exportCsv': 'Export CSV',
    'searchVehiclePlaceholder': 'Search by plate, customer name, case ref...',
    'manageUsersTitle': 'System User Management',
    'manageUsersSub':
        'Manage user roles, account statuses, and reset passwords.',
    'addUser': 'Add User',
    'userHeader': 'User',
    'roleHeader': 'Role',
    'phoneHeader': 'Phone',
    'lastLogin': 'Last Login',
    'historyTitle': 'Scan & Audit History',
    'historySub':
        'Audit logs of all live camera scans, manual search queries, and database changes.',
    'settingsTitle': 'System Settings & AI Parameters',
    'settingsSub':
        'Control AI OCR confidence thresholds, application theme, and language.',
    'languageSetting': 'Interface Language',
    'themeSetting': 'Theme Mode',
    'darkModeLabel': 'Dark Mode',
    'lightModeLabel': 'Light Mode',
    'systemAlertsHeader': 'System Alerts',
    'soundAlertSetting': 'Match Sound Alert',
    'soundAlertSub': 'Play audio chime on critical match alert',
    'detectionConfidenceThreshold': 'YOLO Detection Confidence Threshold',
    'ocrConfidenceThreshold': 'PP-OCR Confidence Threshold',
    'versionInfo': 'App Version',
    'softwareNameLabel': 'Software Name',
    'engineVersionLabel': 'Engine Version',
    'profileTitle': 'User Profile',
    'profileSub': 'View and update your officer credentials & settings.',
    'editProfileInfo': 'Edit Profile Information',
    'fullNameLabel': 'Full Name',
    'phoneNumberLabel': 'Phone Number',
    'emailAddressLabel': 'Email Address',
    'saveProfileBtn': 'Save Profile Changes',
    'changePassword': 'Change Password',
    'oldPassword': 'Current Password',
    'newPassword': 'New Password',
  },
  AppLanguage.bm: <String, String>{
    'appName': 'TRACK',
    'appSubName': 'Sistem Pengesanan & Padanan Nombor Plat Malaysia',
    'navDashboard': 'Papan Utama',
    'navScanner': 'Pengimbas Langsung',
    'navSearch': 'Carian Manual',
    'navVehicles': 'Kenderaan',
    'navUsers': 'Pengguna',
    'navHistory': 'Sejarah Audit',
    'navSettings': 'Tetapan',
    'navProfile': 'Profil',
    'navLogout': 'Log Keluar',
    'moreMenu': 'Menu',
    'demoRole': 'Peranan Demo',
    'roleUser': 'Pengguna',
    'roleAdmin': 'Pentadbir',
    'roleSuperAdmin': 'Penaung Utama',
    'readOnlyBadge': 'Mod Lihat Sahaja',
    'loginTitle': 'Log Masuk ke Track',
    'loginSubtitle': 'Pilih peranan untuk memulakan sesi demo',
    'loginButton': 'Log Masuk Sekarang',
    'totalVehicles': 'Jumlah Kenderaan',
    'activeCases': 'Kes Tunggakan Aktif',
    'todayScans': 'Pengimbasan Hari Ini',
    'manualSearches': 'Carian Manual',
    'quickNav': 'Capaian Pantas',
    'openScannerBtn': 'Buka Pengimbas',
    'searchPlateBtn': 'Cari Nombor Plat',
    'vehiclesRepoBtn': 'Pangkalan Data Kenderaan',
    'auditHistoryBtn': 'Sejarah Audit',
    'recentMatchesTitle': 'Padanan Kes Terkini & Aliran Audit',
    'searchTitle': 'Carian Nombor Plat',
    'searchPlaceholder': 'Contoh: ANN 7569 atau W 8821 X',
    'searchBtn': 'Cari Sekarang',
    'matchFound': 'PADANAN KES DIJUMPAI',
    'possibleMatchFound': 'PADANAN BERPOTENSI DIJUMPAI',
    'noMatchTitle': 'TIADA PADANAN REKOD',
    'noMatchDesc': 'Nombor plat ini tiada dalam rekod tunggakan.',
    'plateNumber': 'Nombor Plat',
    'customerName': 'Nama Pelanggan',
    'vehicleDetails': 'Kenderaan',
    'financeCompany': 'Syarikat Kewangan',
    'caseReference': 'Rujukan Kes',
    'priority': 'Keutamaan',
    'liveScannerTitle': 'Pengimbas ANPR Langsung Malaysia',
    'cameraPreview': 'Pratonton Kamera Langsung',
    'recentDetectionList': 'Senarai Pengesanan Terkini',
    'cameraFps': 'Kamera FPS',
    'detectionFps': 'Pengesanan FPS',
    'confidence': 'Keyakinan AI',
    'manageVehiclesTitle': 'Pengurusan Kenderaan Target',
    'manageVehiclesSub':
        'Tambah, edit, import atau uruskan pangkalan data kes kenderaan.',
    'addVehicle': 'Tambah Kenderaan',
    'importCsv': 'Import CSV',
    'exportCsv': 'Eksport CSV',
    'searchVehiclePlaceholder':
        'Cari nombor plat, nama pelanggan, rujukan kes...',
    'manageUsersTitle': 'Pengurusan Pengguna Sistem',
    'manageUsersSub':
        'Urus peranan pengguna, status akaun dan set semula kata laluan.',
    'addUser': 'Tambah Pengguna',
    'userHeader': 'Pengguna',
    'roleHeader': 'Peranan',
    'phoneHeader': 'Nombor Telefon',
    'lastLogin': 'Log Masuk Terakhir',
    'historyTitle': 'Sejarah Pengimbasan & Audit',
    'historySub':
        'Log audit semua pengimbasan kamera langsung, carian manual dan kemaskini pangkalan data.',
    'settingsTitle': 'Tetapan Sistem & Parameter AI',
    'settingsSub':
        'Kawal threshold keyakinan AI OCR, tema aplikasi dan bahasa.',
    'languageSetting': 'Bahasa Antaramuka',
    'themeSetting': 'Mod Tema',
    'darkModeLabel': 'Mod Gelap',
    'lightModeLabel': 'Mod Terang',
    'systemAlertsHeader': 'Amaran Sistem',
    'soundAlertSetting': 'Bunyi Amaran Padanan',
    'soundAlertSub': 'Mainkan bunyi amaran semasa padanan kes dikesan',
    'detectionConfidenceThreshold': 'Threshold Keyakinan Pengesanan YOLO',
    'ocrConfidenceThreshold': 'Threshold Keyakinan PP-OCR',
    'versionInfo': 'Versi Aplikasi',
    'softwareNameLabel': 'Nama Perisian',
    'engineVersionLabel': 'Versi Enjin',
    'profileTitle': 'Profil Pengguna',
    'profileSub': 'Semak dan kemaskini maklumat profil & perincian pegawai.',
    'editProfileInfo': 'Kemaskini Maklumat Profil',
    'fullNameLabel': 'Nama Penuh',
    'phoneNumberLabel': 'Nombor Telefon',
    'emailAddressLabel': 'Alamat Emel',
    'saveProfileBtn': 'Simpan Perubahan Profil',
    'changePassword': 'Tukar Kata Laluan',
    'oldPassword': 'Kata Laluan Asal',
    'newPassword': 'Kata Laluan Baharu',
  },
};

String localizedText(AppLanguage language, String key) {
  return _localizedText[language]?[key] ??
      _localizedText[AppLanguage.en]?[key] ??
      key;
}
