import { PlateCategory, PlateLayout } from '../db/types';

export interface ValidationTestCase {
  id: string;
  groundTruthPlate: string;
  normalizedGroundTruth: string;
  displayPlate: string;
  expectedCategory: PlateCategory;
  layout: PlateLayout;
  backgroundType: 'BLACK' | 'WHITE' | 'RED' | 'GREEN';
  vehicleType: string;
  lighting: 'DAYLIGHT' | 'NIGHT' | 'PARKING' | 'HEADLIGHT_GLARE' | 'RAIN';
  movement: 'STATIC' | 'MOVING_VEHICLE' | 'MOVING_CAMERA';
  visiblePlatesCount: number;
  expectedMatchStatus: 'EXACT' | 'POSSIBLE' | 'NONE' | 'CLOSED';
}

export const VALIDATION_MANIFEST: ValidationTestCase[] = [
  {
    id: 'tc-01',
    groundTruthPlate: 'A1234',
    normalizedGroundTruth: 'A1234',
    displayPlate: 'A 1234',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-02',
    groundTruthPlate: 'AB1234',
    normalizedGroundTruth: 'AB1234',
    displayPlate: 'AB 1234',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'POSSIBLE',
  },
  {
    id: 'tc-03',
    groundTruthPlate: 'ABC1234',
    normalizedGroundTruth: 'ABC1234',
    displayPlate: 'ABC 1234',
    expectedCategory: 'MOTORCYCLE',
    layout: 'TWO_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Motorcycle',
    lighting: 'DAYLIGHT',
    movement: 'MOVING_VEHICLE',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-04',
    groundTruthPlate: 'W1234A',
    normalizedGroundTruth: 'W1234A',
    displayPlate: 'W 1234 A',
    expectedCategory: 'LETTER_NUMBER_SUFFIX',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-05',
    groundTruthPlate: 'KV1234E',
    normalizedGroundTruth: 'KV1234E',
    displayPlate: 'KV 1234 E',
    expectedCategory: 'LANGKAWI',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'CLOSED',
  },
  {
    id: 'tc-06',
    groundTruthPlate: 'EV1234',
    normalizedGroundTruth: 'EV1234',
    displayPlate: 'EV 1234',
    expectedCategory: 'EV_SPECIAL',
    layout: 'SINGLE_LINE',
    backgroundType: 'WHITE',
    vehicleType: 'Electric SUV',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-07',
    groundTruthPlate: 'PUTRAJAYA1234',
    normalizedGroundTruth: 'PUTRAJAYA1234',
    displayPlate: 'PUTRAJAYA1234',
    expectedCategory: 'PUTRAJAYA',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-08',
    groundTruthPlate: 'SAB1234',
    normalizedGroundTruth: 'SAB1234',
    displayPlate: 'SAB 1234',
    expectedCategory: 'SABAH',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Pickup',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-09',
    groundTruthPlate: 'QAA1234',
    normalizedGroundTruth: 'QAA1234',
    displayPlate: 'QAA 1234',
    expectedCategory: 'SARAWAK',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Pickup',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-10',
    groundTruthPlate: '1122DP',
    normalizedGroundTruth: '1122DP',
    displayPlate: '1122DP',
    expectedCategory: 'DIPLOMATIC',
    layout: 'SINGLE_LINE',
    backgroundType: 'RED',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-11',
    groundTruthPlate: 'ABC9999',
    normalizedGroundTruth: 'ABC9999',
    displayPlate: 'ABC 9999',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'NIGHT',
    movement: 'MOVING_CAMERA',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-12',
    groundTruthPlate: 'WXY77B8',
    normalizedGroundTruth: 'WXY77B8',
    displayPlate: 'WXY 77 B8',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'POSSIBLE', // Matches WXY7788 via B -> 8 confusion
  },
  {
    id: 'tc-13',
    groundTruthPlate: 'WWW1',
    normalizedGroundTruth: 'WWW1',
    displayPlate: 'WWW 1',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Proton hatchback rear',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-14',
    groundTruthPlate: 'B20',
    normalizedGroundTruth: 'B20',
    displayPlate: 'B 20',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Toyota sedan front',
    lighting: 'DAYLIGHT',
    movement: 'MOVING_CAMERA',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-15',
    groundTruthPlate: 'A1',
    normalizedGroundTruth: 'A1',
    displayPlate: 'A 1',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'BMW front',
    lighting: 'NIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-16',
    groundTruthPlate: 'QAB1234',
    normalizedGroundTruth: 'QAB1234',
    displayPlate: 'QAB 1234',
    expectedCategory: 'SARAWAK',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Nissan pickup',
    lighting: 'RAIN',
    movement: 'MOVING_VEHICLE',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'POSSIBLE',
  },
  {
    id: 'tc-17',
    groundTruthPlate: 'JQ1234',
    normalizedGroundTruth: 'JQ1234',
    displayPlate: 'JQ 1234',
    expectedCategory: 'STANDARD',
    layout: 'TWO_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Motorcycle',
    lighting: 'DAYLIGHT',
    movement: 'MOVING_VEHICLE',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-18',
    groundTruthPlate: 'MALAYSIA200',
    normalizedGroundTruth: 'MALAYSIA200',
    displayPlate: 'MALAYSIA 200',
    expectedCategory: 'SPECIAL_SERIES',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Mercedes rear',
    lighting: 'HEADLIGHT_GLARE',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-19',
    groundTruthPlate: 'PUTRAJAYA1',
    normalizedGroundTruth: 'PUTRAJAYA1',
    displayPlate: 'PUTRAJAYA 1',
    expectedCategory: 'PUTRAJAYA',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Mazda rear',
    lighting: 'PARKING',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-20',
    groundTruthPlate: 'VEP1234',
    normalizedGroundTruth: 'VEP1234',
    displayPlate: 'VEP 1234',
    expectedCategory: 'INSTITUTIONAL',
    layout: 'SINGLE_LINE',
    backgroundType: 'WHITE',
    vehicleType: 'Imported vehicle',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-21',
    groundTruthPlate: 'ABC12345',
    normalizedGroundTruth: 'ABC12345',
    displayPlate: 'ABC 12345',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Large commercial vehicle',
    lighting: 'DAYLIGHT',
    movement: 'MOVING_VEHICLE',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
];
